apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.servicetype}}
  selector:
    app: colorapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080